### ISSUE TITLE
Support for Java 9

### ISSUE THREAD

**Issue by maikelvallinga** [theia-ide/yang-lsp#101]
Tried to build as described, but get error: Could not determine java version from '9.0.1'
I've installed java JDK 9.0.1 and upgraded gradle to the latest version. On the gradle web page i see that the issue is seen in earlier gradle versions. How to solve this issue?

**Comment by maikelvallinga** [comment]
I've downgraded java to version 8 and this works. So there is a workaround available.

**Comment by JanKoehnlein** [comment]
Does
   ./gradlew wrapper --gradle-version 4.6
help?

**Comment by JanKoehnlein** [comment]
Fixed
