### ISSUE TITLE
a list which uses imported grouping and taking imported leaf (defined in grouping) as key

### ISSUE THREAD

**Issue by huyuwen** [theia-ide/yang-lsp#106]
https://github.com/theia-ide/yang-lsp/blob/748837ef27555ad1fafffe32ae24eabc815edb64/yang-lsp/io.typefox.yang.diagram/src/main/java/io/typefox/yang/diagram/YangDiagramGenerator.xtend#L193

In yang-dep.yang, there is a grouping g1
`    grouping g1 {
        leaf g-leaf {
            type string;
        }
    }
`
In yangster-test.yang, there is a list l1
`	list l1 {
		key g-leaf;
		uses ydep:g1;
	}
`
In this case, it will cause problem to fetch SLabel from elementIndex with keyRefence.node as key.
Then there will be a NPE when invoke leafElement.text

**Comment by JanKoehnlein** [comment]
How would you like such a "foreign key" to be represented in the diagram?

**Comment by huyuwen** [comment]
Currently, I think the bug fix solution is good enough. 
As for "foreign key", we need to discuss for it.
