### ISSUE TITLE
ScopeContextProvider.computeScope load the same resource as two different objects. Windows Issue

### ISSUE THREAD

**Issue by huyuwen** [theia-ide/yang-lsp#107]
https://github.com/theia-ide/yang-lsp/blob/748837ef27555ad1fafffe32ae24eabc815edb64/yang-lsp/io.typefox.yang/src/main/java/io/typefox/yang/scoping/ScopeContextProvider.xtend#L409

We found when linker return importedModule and related objects. It will load same resources into two YangResources or ObjectURIs due to URI in windows.
Take t-common.yang as example, it will report 'include t-meta-extensions' and 'include t-cli-extensions' has error due to t-common module are not the belongs-to module. Issue from L459 "belongingModule !== module"
Actually, here belongingModule and module point to the same physical file resource. the only different between the two objects is the URI of their YangResource which the object was loaded from are 'different' like 
uri='file:///c%3A/Users/myid/workspace/eoi_repo/tailf/tailf-common.yang'
uri='file:///c:/Users/mid/workspace/eoi_repo/tailf/tailf-common.yang'.

So the root cause here is why the same resource in Windows will be loaded as two different resources.
One of them take ':' into URI, but another take '%3A' into URI. Maybe there missed some formalize step?

The similar behavior also cause the Issue from L445, there are multi revision module matches. But in fact, there are no multi revisions at all.

**Comment by JanKoehnlein** [comment]
See https://github.com/eclipse/xtext-core/issues/528

**Comment by JanKoehnlein** [comment]
Fied
