### ISSUE TITLE
Assert will be failed in Windows

### ISSUE THREAD

**Issue by huyuwen** [theia-ide/yang-lsp#112]
https://github.com/theia-ide/yang-lsp/blob/37787053a252ddaee2d08dc200f5e7f6b55896fb/yang-lsp/io.typefox.yang.diagram/src/test/java/io/typefox/yang/diagram/test/DiagramGeneratorTest.xtend#L22

This assert will be failed due to Windows line delimiter '\r\n' in target toString

**Comment by JanKoehnlein** [comment]
Fixed
