### ISSUE TITLE
XpathExpression doesn't accept Concatenated String

### ISSUE THREAD

**Issue by huyuwen** [theia-ide/yang-lsp#113]
In recent tests, we found that XpathExpression doesn't accept those string that are concatenated with two segament and connection with '+'. 
There are 3 statements are impacted, When, Must, and Path. All xpath expression which used in the 3 statement which has '+' couldn't be loaded correctly.
For instance: 
path "/qosipos:qos/qosipos:congestion-avoidance-"
        + "map/qosipos:map-name"
must "number(.) <= number(../../rate-num/rate-"
                + "num)"

All these examples mostly have the same feature, breaking one word into two parts.
"congestion-avoidance-map"  -> "congestion-avoidance-" + "map"
"rate-num" -> "rate-" + "num"

It is not mandatory to have '-' in these strings. any break word will cause problem.

**Comment by svenefftinge** [comment]
Yes, that is a known limitation. You need to break xpath expressions on token-boundaries.
E.g. the following should work:
```
path "/qosipos:qos/qosipos:congestion-avoidance-map"
+ "/qosipos:map-name"
must "number(.) <= number(../../rate-num/"
+ "rate-num)"

```

**Comment by huyuwen** [comment]
Well, I know that breaking xpath expressions on token-boundaries works. 
This issue will make our tools non backward compatible. Previously, we accepted the xpath expression which in my example. But now, user have to re-format quite a lot of their xpath expression, otherwise the tool couldn't continue to work.
Is it too costly to fix this limitation?

**Comment by svenefftinge** [comment]
Maybe there is another way we can improve the situation for users? E.g. having a special validation and quickfix?

**Comment by huyuwen** [comment]
From our point of view, we hope that tools could be backward compatible as much as possible. So is it possible to construct/merge these kind of concatenated strings into one string before parsing as XpathExpression?

As to special validation, could you give us an example?
Regarding to quickfix, of cause, it is good to have from IDE. But the real situation is, we couldn't force all our users to use Yang IDE (whatever yangster, theia, eclipse, etc.). 
Some of our user even don't use IDE at all. They generate yang file from CLI tools. In this case, there is no chance to run this kind of quickfix.

**Comment by huyuwen** [comment]
Right, I have suggested them to do small improvements regarding to the line break behaviors. But I haven't get their response. What kind of CLI tool could you provide to us?

**Comment by svenefftinge** [comment]
Something that applies the quick fixes mentioned above. But it would be really much better if that was fixed where it is caused.

**Comment by huyuwen** [comment]
When could you provide such a CLI tool in case we can't get it fixed where it is caused.

**Comment by JanKoehnlein** [comment]
I could start working on it now.

**Comment by JanKoehnlein** [comment]
Is that enough or should I wrap that into an executable jar?

**Comment by huyuwen** [comment]
Let me try with the two solutions, will come back to you soon.

**Comment by JanKoehnlein** [comment]
sed's regexps are a bit different on all machines. The one above works on my Mac. Here are some alternatives
```
cat my.yang | sed 's/"\s*\+\s*"//g'
cat my.yang | sed -e 's/"\s*\+\s*"//g'
cat my.yang | sed -E 's/"\s*\+\s*"//g'
```

**Comment by spoenemann** [comment]
Let's reopen this in case more tools / quick-fixes are needed.

**Comment by andreasjakobik** [comment]
Hello,

Can we please reopen this case? We face problems still with autogenerated yang files where must, when and path expressions have been chopped up in non token boundaries. 

We have built for our own tools a fixer, but it does not help when viewing the modules in Yangster on VSCode or Theia environments.  

Other open source or commercial tools such as pyang and Confd accepts the concatenated strings where token boundaries have been broken, so yang-lsp unfortunately "looks bad" here. 

Since the generated yang files must not be touched, yang-lsp should accept them as is. 

Thanks,
Andreas

**Comment by dhuebner** [comment]
@andreasjakobik 
Is that mainly about a possibility to split inside the ID?  
`"../acl-protocol"` - > `"../acl-" + "protocol"`
... or do you have other cases in generated yang files like e.g. split before a colon?
`"/ecertm:certm/ecertm:user-label"` -> `"/ecertm:certm/ecertm:" + "user-label"`

**Comment by andreasjakobik** [comment]
Yeah, beleive so. Seems you find a solution then? Thanks!

**Comment by dhuebner** [comment]
@andreasjakobik 
> Seems you find a solution then? 

Yes, after talking to @svenefftinge we found a good solution. All existing tests are passing and I added a bit more for Xpath too. Please let me know if there are any drawbacks in tooling or serialization on your side. 

Overall I think this one can finally be closed

**Comment by dhuebner** [comment]
@andreasjakobik 
Did you had a chance to try it out with a nightly build?

**Comment by andreasjakobik** [comment]
@dhuebner 
Just tested and it works like a charm! The validator utility we have now reports 0 errors 0 warnings on a file that previously had a lot of errors and warnings. 

We ususually wait for an official release to test, so that we can easily pull a new version from repo https://repo1.maven.org/maven2/io/typefox/yang/io.typefox.yang/ but it was not a problem really to clone repo, build and use the _**io.typefox.yang-0.4.0-SNAPSHOT.jar**_ instead. 

Thanks!

**Comment by dhuebner** [comment]
@andreasjakobik 
> Just tested and it works like a charm! 

Glad to hear!

@spoenemann  and @kaisalmen are currently working on setup for GitHub action to prepare a release. So I hope you and others can consume 0.4.0 release soon.

**Comment by andreasjakobik** [comment]
Sorry... :-)

Upon further testing, broken augment paths still pose a problem. Here is an example:

```
augment "/if:interfaces/if:interface/ethxrouter6000:ethernet/l"
  + "2servicer6k:service-instance" {
```
When putting all in one line it is fine.

**Comment by dhuebner** [comment]
@andreasjakobik 
`augment`  uses `SchemaNodeIdentifier` and not the Xpath see my comment above https://github.com/theia-ide/yang-lsp/issues/113#issuecomment-824024678 

`SchemaNodeIdentifier` is a bit different to Xpath expression and need to be handled separately.  Should I reopen this one or create a new issue?

**Comment by andreasjakobik** [comment]
@dhuebner 
I can create a new one if you wish.

**Comment by dhuebner** [comment]
@andreasjakobik 
I would prefer a new Issue because the possible solution might be different to one for Xpath

**Comment by andreasjakobik** [comment]
@dhuebner 
Sure, #205 has been created.
