### ISSUE TITLE
Support external library pathes

### ISSUE THREAD

**Issue by svenefftinge** [theia-ide/yang-lsp#115]
It would be good to allow external paths and zips to include.
See https://github.com/theia-ide/yang-vscode/issues/4

**Comment by JanKoehnlein** [comment]
You can add these libs as `yangPath in the `yang.settings` file in your home folder or in the workspace root now. 
Entries can be yang file names, directory names or zip file names (all absolute) in OS specific syntax, separated by the OS specific path separator.

Example
```
{
    "yangPath": "/path/to/rift.zip:/some/special/my.yang:/some/dir/containing/yang/files",
}
```
