### ISSUE TITLE
XpathExpression Serialization will duplicate prefix in certain case.

### ISSUE THREAD

**Issue by huyuwen** [theia-ide/yang-lsp#119]
I defined a new module called xpath-serialize.yang which import yangster-test.yang to create leafref.
`module xpath-serialize {

    prefix xs;

    import yangster-test {
	prefix ytest;
    }

    container cb {
        list lb {
            leaf lfb {
                type leafref {
                    path "/ytest:c1/ytest:l1";
                }
            }
        }
    }`

In ModuleSerializeTest, I add a new test cases.
`
	def void testSerializeOriginalXPath() {

		val targetModule = loadModuleFile("xpath-serialize.yang")
		EcoreUtil.resolveAll(targetModule)
		val resource = targetModule.eResource as XtextResource
		val result = resource.serializer.serialize(targetModule)
		System.out.println(result)

	}
`
After running test case, the result shows,

`    container cb {

        list lb {
            leaf lfb {
                type leafref {
                    path /ytest:ytest:c1/ytest:ytest:l1;
                }
            }
        }
    }`
prefix "ytest" is duplicated. I debug a little bit and found that CrossReferenceSerializer  and YangSerializerScopeProvider are involved in this issue.
If I don't resolveAll the targetModule, then serialization works correctly.
But if we resolveAll the targetModule, then duplication occurs.
And this problem only happens to the crossreference to another yang module.
So I think if an EObject is still a Proxy object, then serializer will choose  CrossReferenceSerializer:87. In this case, (without resolveAll), serialzation wors correctly.
But if resolveAll is used, then CrossReferenceSerializer:119 will be reached, and next YangSerializerScopeProvider will return a AliasEObjectDescription which include the prefix in the name.

Attached xpath-serialize.yang.txt, please rename it.
[xpath-serialize.yang.txt](https://github.com/theia-ide/yang-lsp/files/2013236/xpath-serialize.yang.txt)

**Comment by JanKoehnlein** [comment]
Fixed
