### ISSUE TITLE
CrossReference in XPathExpression doesn't reference to correct target

### ISSUE THREAD

**Issue by huyuwen** [theia-ide/yang-lsp#120]
We have module-a and module-b. module-a has container,c1/list,l1/leaf,lf1, module-b has container,c1/leaf,lf1. In module-a, we define a leafref to referenc to module-b: /mb:c1/mb:lf1.

We can find /mb:c1 will point to module-a:c1. That's acutally wrong. simply to say that prefix is not considered here.
![chrome_2018-05-17_15-24-44](https://user-images.githubusercontent.com/809513/40180159-75e6709a-59e6-11e8-8ec3-2a21b18f59d5.png)

Further more, in the Path, if we just use an non-exists prefix, there won't be any errors.
For example, path "/mc:c1/mb:lf1".

**Comment by JanKoehnlein** [comment]
To implement the validation properly, we'd have to execute/evaluate all kinds of Xpath elements. I think this is currently out of scope. I will close this issue as the main problem is solved.
