### ISSUE TITLE
New method resolveModelPrefix() doesn't consider current module itself

### ISSUE THREAD

**Issue by huyuwen** [theia-ide/yang-lsp#123]
https://github.com/theia-ide/yang-lsp/blob/de2e2371e7bc6c49f030bebb5a83db3e6f55776e/yang-lsp/io.typefox.yang/src/main/java/io/typefox/yang/scoping/xpath/XpathResolver.xtend#L345

In this method, the input linkName could also be current modules node name with current module's its own prefix. But the logic only consider imported module. See the example,

`module m_a {

      prefix ma;

      leaf lA {
            type leafref {
                  path '/ma:lm/ma:state';
            }
      }

      container lm {
            leaf state {
                  type string;
            }
      }
}`

Here in this example, prefix ma are actually point to current module m_a itself. But in resolveModelPrefix(), this prefix 'ma' couldn't be found in imported module.

**Comment by JanKoehnlein** [comment]
Doesn't it work anyway? The logic should go on with the simple name then.

**Comment by huyuwen** [comment]
No, I don't think it works. Because the path will always be a proxy. I think Linker couldn't find the correct target node.

**Comment by JanKoehnlein** [comment]
Fixed
