### ISSUE TITLE
[Discusion] Is it better to move Choice and Case into SchemaNode

### ISSUE THREAD

**Issue by huyuwen** [theia-ide/yang-lsp#135]
https://github.com/theia-ide/yang-lsp/blob/094e039770307fb501df89bd3657c72cbe266c6e/yang-lsp/io.typefox.yang/src/main/java/io/typefox/yang/Yang.xtext#L46

According to RFC7950, Choice and Case are only schema node, but not data definition node, whether it is better to move the two kinds of node out from DataSchemaNode into SchemaNode?

Is there any special logic or reason to have current definition in Yang.xtext?

**Comment by JanKoehnlein** [comment]
> Is there any special logic or reason to have current definition in Yang.xtext?
Nothing I am aware of.
