### ISSUE TITLE
Server does not respond to initialize message

### ISSUE THREAD

**Issue by dimbleby** [theia-ide/yang-lsp#140]
Client sends a message something like this:

```json
{"method": "initialize", "jsonrpc": "2.0", "id": 1, "params": {"initializationOptions": {}, "rootUri": "file:///path/to/project", "capabilities": {}, "rootPath": "path/to/project", "processId": 12345}}
```

Expect a response declaring the server capabilities, something like this:

```json
{"jsonrpc":"2.0","id":1,"result":{"capabilities":{"textDocumentSync":2,"hoverProvider":true,"completionProvider":{"resolveProvider":false,"triggerCharacters":[".",":",">","#","<","\"","/"]},"signatureHelpProvider":{"triggerCharacters":["(",","]},"definitionProvider":true,"typeDefinitionProvider":true,"implementationProvider":true,"referencesProvider":true,"documentHighlightProvider":true,"documentSymbolProvider":true,"workspaceSymbolProvider":true,"codeActionProvider":true,"codeLensProvider":{"resolveProvider":false},"documentFormattingProvider":false,"documentRangeFormattingProvider":false,"renameProvider":true,"documentLinkProvider":{"resolveProvider":true},"executeCommandProvider":{"commands":[]}}}}
```

(That response is taken from a different language server).

But in fact there is no response from this server.

In particular the client that I am using is expecting the server to declare its capabilities - and since it hasn't, it assumes that the server is very not capable.  So I'm unable to go to definition, find references, etc.

**Comment by dimbleby** [comment]
So on further investigation it turns out that the server is claiming that the `initialize` request is cancelled:

```json
{"jsonrpc":"2.0","id":1,"error":{"code":-32800,"message":"The request (id: 1, method: \u0027initialize\u0027) has been cancelled"}}
```

though there's certainly no explicit cancellation taking place from the client.

But, having tried now with three language server clients - only the first is seeing this behaviour.  So I suppose that client must be doing *something* to provoke it.

I guess I'll raise an issue over at that project.  If you can provide any insight as to what causes the server to believe that this request has been cancelled, that would be very helpful.

Thanks!

**Comment by dimbleby** [comment]
Very plausible suggestion in w0rp/ale#2295 that the issue is that the client is not sending the 'initialized' message.

Would that lead to these symptoms?  If so, this would put the ball almost entirely back in the client's court - except WIBNI if the server's error message were more helpful,

**Comment by dimbleby** [comment]
Very plausible suggestion in w0rp/ale#2295 that the issue is that the client is not sending the 'initialized' message.

Would that lead to these symptoms?  If so, this would put the ball almost entirely back in the client's court - except WIBNI the server's error message were more helpful,

**Comment by w0rp** [comment]
ALE does send that message before sending any other messages. Don't confuse people.

**Comment by spoenemann** [comment]
This project uses [Xtext](https://github.com/eclipse/xtext-core) as language server framework. If there is an issue regarding initialization, it should most likely be fixed there.

The main implementation class is https://github.com/eclipse/xtext-core/blob/master/org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/LanguageServerImpl.java

**Comment by spoenemann** [comment]
From what I can see from the code, the Xtext language server won't send any diagnostics before the client has sent 'initialized'. But I don't know what could cause the cancellation.
