### ISSUE TITLE
How do I start LSP Server

### ISSUE THREAD

**Issue by deepakagra** [theia-ide/yang-lsp#148]
I could build codebase as per instructions mentioned here.  I intend to use yang-lsp with Yangster. Now, how do I run my yang-lsp server so that it can connect to yangster ! when I try ./gradlew run ; it merely run all test cases.

**Comment by huyuwen** [comment]
You don't need to launch yang-lsp server manually for yangster. In yangster project, there has two example apps, yangster-app and yangster-app-electron. You can directly get into the two folders and then use 'yarn start' to start a certain app.

**Comment by kittaakos** [comment]
@deepakagra, did you figure out a solution for your issue? Let me know if there is anything I can assist you.

**Comment by spoenemann** [comment]
The server is not started manually, but the Yangster extension does it:

https://github.com/theia-ide/yangster/blob/a2def39dcd32650bf33c7efa0bc9e4a6c74b0636/theia-yang-extension/src/backend/backend-extension.ts#L53

There is an alternative for development, though: Import this project in Eclipse (as Gradle project) and start the YangServerSocketLauncher main class, then start yangster-app with `yarn start:socket`.
