### ISSUE TITLE
Yang Outline Issue

### ISSUE THREAD

**Issue by huyuwen** [theia-ide/yang-lsp#149]
We have some yang modules which has a few revisions with different dates. For instance,
```
module abc {
    revision 2018-10-10 {
          ext:version 4;
          ext:release 5;
          ext:correction 6;
    }
    revision 2018-09-10 {
          ext:version 1;
          ext:release 2;
          ext:correction 3;
    }
}
```
But in the yangster outline view, module a's outline looks like, 
```
abc.4
abc.5
abc.6
abc.1
abc.2
abc.3
```
Actually, the outline should looks like,
```
2018-10-10
  --version 4
  --release 5
  --correction 6
2018-09-10
  --version 1
  --release 2
  --correction 3
```

So basiclly, I think, is this bug related to GH-144: Switched to the hierarchical document symbols in the outline?

**Comment by kittaakos** [comment]
@huyuwen, your example produces errors. Correct me if I am wrong, but [a `revision` statement can have one `description` and one `reference` sub-statement](https://tools.ietf.org/html/rfc7950#section-7.1.9). Most likely I am missing something. Can you please provide me an example I can transform into test cases? Thank you!

**Comment by huyuwen** [comment]
Hi Kittaakos,
Sorry, I miss your reply last week. This is the complete test case.
```
module abc {
    yang-version 1.1;
    namespace abc;
    prefix a;
    revision 2018-10-10 {
          a:version 4;
          a:release 5;
          a:correction 6;
    }
    revision 2018-09-10 {
          a:version 1;
          a:release 2;
          a:correction 3;
    }
    extension version {
        argument value;
    }
    extension release {
        argument value;
    }
    extension correction {
        argument value;
    }
}
```

**Comment by kittaakos** [comment]
Thank you, @huyuwen!

**Comment by huyuwen** [comment]
@kittaakos, There is no need to get rid of extension from outline. The new outline looks much better.
The only thing need to be improved is the unknow statement in revision.
```
2018-10-10
  abc.version.4
  abc.release.5
  abc.correction.6
2018-09-10
  abc.version.1
  abc.release.2
  abc.correction.3
version
  abc.version.value
release
  abc.release.value
correction
  abc.correction.value
```
The extension name should also be shown in outline, but not only the prefix.

**Comment by kittaakos** [comment]
Thanks for the feedback, I adjust the PR.

**Comment by kittaakos** [comment]
After the adjustment, the outline is this:

![screen shot 2018-11-12 at 13 50 58](https://user-images.githubusercontent.com/1405703/48348628-2d015880-e682-11e8-8623-297d5b886f7a.jpg)
