### ISSUE TITLE
how to disable the snapshot

### ISSUE THREAD

**Issue by RimShao** [theia-ide/yang-lsp#165]
Hi Jan,

In the latest theia ide, there is one .snapshot folder to regular backup my yang workspace,  that cause a lot of duplication module existed warnings.

The question is how to close the .snapshot feature ? I try the preferences but did not mange find it.

or something could customized manged in .theia/settings.json ?

Thanks

**Comment by spoenemann** [comment]
Hi Rim, I believe the .snapshot folders are not related to Theia. Could that be a feature of your operating system?

**Comment by RimShao** [comment]
That's a good point, I will investigate that on our ubuntu os.  Thanks.

**Comment by spoenemann** [comment]
Please reopen if any action is required in yang-lsp.
