### ISSUE TITLE
Serialization of concatenated must expression removes trailing space

### ISSUE THREAD

**Issue by andreasjakobik** [theia-ide/yang-lsp#166]
Hello,

Here is another example of serialization problem, now with dire consequences.

The following yang is parsed in:
```
        container second-tag {
          must
            '../outer-tag/tag-type = "dot1q-types:s-vlan" and ' +
            'tag-type = "dot1q-types:c-vlan"' {
```

And here is what comes out when serializing the same model:
```
          container second-tag {
                    must '../outer-tag/tag-type = "dot1q-types:s-vlan" and' +
            'tag-type = "dot1q-types:c-vlan"' {
```

Notice the space has been removed after "and " causing the expression to be invalid. 

Thanks,
Andreas

**Comment by spoenemann** [comment]
The issue is still present when formatting is enabled in the serializer's SaveOptions.
