### ISSUE TITLE
Updating the Xtext Community Website

### ISSUE THREAD

**Issue by miklossy** [theia-ide/yang-lsp#167]
Hello Yang-LSP team,

The Xtext team would like to update the [Xtext community website](https://www.eclipse.org/Xtext/community.html) listing all the cool projects people are building around Xtext/Xtend.

See also the corresponding [GitHub issue](https://github.com/eclipse/xtext/issues/1541) and [Bugzilla ticket](https://bugs.eclipse.org/bugs/show_bug.cgi?id=328477).

If you are interested that the Yang-LSP project is listed there, please provide the following information as a comment to this issue:

```
<tr>
	<td><a href="project_link">project_name</a></td>
	<td>project_description_max_2_sentences</td>
	<td>license</td>
	<td>category</td>
	<td>author(s)</td>
</tr>

```
We will then update the Xtext community website and get it online as soon as possible.

Thanks!
Tamás

**Comment by spoenemann** [comment]
```
<tr>
	<td><a href="https://github.com/theia-ide/yang-lsp">YANG Language Server</a></td>
	<td>A language server for the YANG data modeling language</td>
	<td>Apache License 2.0</td>
	<td>Language Server</td>
	<td>TypeFox, Ericsson</td>
</tr>
```

**Comment by miklossy** [comment]
Thank you @spoenemann !

**Comment by miklossy** [comment]
The `YANG Language Server` project has been added to the [Xtext community website](https://www.eclipse.org/Xtext/community.html).
