### ISSUE TITLE
null uriToProblem in validation issue

### ISSUE THREAD

**Issue by RimShao** [theia-ide/yang-lsp#196]
Hi, 

In certain syntax issue  'uriToProblem' is null, right now we need additionally to fill the 'URI' value into Issues, otherwise can't resolve file the syntax errors report to. it would be great that yang-lsp can fix that.

use below test model can reproduce the problem, the syntax error is because of unbalanced brace in 'when' statement.

```
leaf key-id {
        type string;

        when "/ctxsr6k:contexts/ctxr6k:context/ctxr6k:context-"
             + "name='local'" {
                  description
                  "";
         }
         }
}
```

**Comment by dhuebner** [comment]
@RimShao 
Would resource URI as `uriToProblem` work for you?

**Comment by dhuebner** [comment]
Fixed
