### ISSUE TITLE
duplicated org.w3c.dom package in xml-apis.jar and java 11

### ISSUE THREAD

**Issue by RimShao** [theia-ide/yang-lsp#217]
Hi, 

In Java 11 developing environment, io.typefox.yang has duplicated org.w3c.dom issue in eclipse.

```
The package org.w3c.dom is accessible from more than one module: <unnamed>, java.xml
```

The reason because org.w3c.dom package is both included in jdk11 jar by default and xml-apis.jar, transitive dependency of io.typefox.yang, It will be great this issue can be solved in io.typefox.yang? Thanks.

**Comment by dhuebner** [comment]
We will need to update to a newer lsp4j >= 0.12, xtext >= 2.26.0 and Java 11

**Comment by dhuebner** [comment]
Using Java 11 now instead of Java 1.8.

Following updates were made:
- Xtext   2.20   > 2.25
- Lsp4j   0.8.1  > 0.10
- Sprotty 0.8.0  > 0.9
- Elk     0.6.0  > 0.7.0
- Mwe2    2.11.1 > 2.12.1
- Xerces  2.12.0 > 2.12.2
