### ISSUE TITLE
[formatter] Don't rely on NodeSemanticRegion

### ISSUE THREAD

**Issue by svenefftinge** [theia-ide/yang-lsp#80]
In https://github.com/theia-ide/yang-lsp/blob/master/yang-lsp/io.typefox.yang/src/main/java/io/typefox/yang/formatting2/YangFormatter.xtend#L458 we assume an implementation of `NodeSemanticRegion` which results in : 

```
java.lang.ClassCastException: org.eclipse.xtext.formatting2.regionaccess.internal.StringSemanticRegion cannot be cast to org.eclipse.xtext.formatting2.regionaccess.internal.NodeSemanticRegion
        at io.typefox.yang.formatting2.YangFormatter.formatMultilineString(YangFormatter.java:618)
        at io.typefox.yang.formatting2.YangFormatter._format(YangFormatter.java:158)
```

when serializing a yang model, created programmatically.

**Comment by JanKoehnlein** [comment]
https://github.com/theia-ide/yang-lsp/pull/92

**Comment by JanKoehnlein** [comment]
PR merged.
