### ISSUE TITLE
YangExtensions getMainModule(EObject obj) will throw out unexpected exception

### ISSUE THREAD

**Issue by huyuwen** [theia-ide/yang-lsp#81]
In the following method, if obj.eContainer is null, this method will throw out unexpected exception.
	def dispatch Module getMainModule(EObject obj) {
		return obj.eContainer.mainModule
	}
In fact this happens when we are trying to fetch an inexist extension's main module.

This getMainModule should be more robust.

**Comment by JanKoehnlein** [comment]
Would this work? https://github.com/theia-ide/yang-lsp/pull/84

**Comment by JanKoehnlein** [comment]
PR merged.

**Comment by huyuwen** [comment]
HI Jan,
Sorry to say that your fix seems not works fine.

I mentioned in my description. The obj.eContainer is null, but not only obj.

So maybe this statement would be better,  obj?.eContainer?.mainModule

What do you think?

**Comment by huyuwen** [comment]
Yes, I test the new method.
It works fine now to just return null.
