### ISSUE TITLE
'_' and ' ' is not accept by Typefox yang parser, but it is accepted by pyang 1.7.3

### ISSUE THREAD

**Issue by huyuwen** [theia-ide/yang-lsp#83]
We defined a string type with patten.
type string {
	pattern '[a-zA-Z0-9-_ ]+';
}

Yang parser with report this pattern is invalid due to '_' and ' '.
But pyang 1.7.3 accept this kind of pattern.

I think that '_' and ' ' is valid

**Comment by JanKoehnlein** [comment]
I get _Invalid regular expression pattern_ and I think it is OK, because the '-' after the '9' is not allowed as the '9' is already the right operand of the range '0-9'. Without the '-' after '9' it works nicely. If you want to include the '-' char you have to quote it as '\-'. So to me this looks like a missing validation in pyang.

Please don't hesitate to reopen if I missed something.

**Comment by huyuwen** [comment]
Hi Jan,
I can understand your explaination. But in our yang module, there are two smiliar types.
type string1 {
	pattern '[a-zA-Z0-9-]+';  // Yang Parser accepted
}
type string2 {
	pattern '[a-zA-Z0-9-_]+'   // Yang Parser report as error;
}
The only difference between the two pattern is one '_'.
So here I would like to figure out whether it is the last '-' or the last '_', which trigger the validation error.
Because according to my understanding to your words, the two patterns should be wrong both.

**Comment by huyuwen** [comment]
Hi Jan,
I can understand your explaination. But in our yang module, there are two smiliar types.
type string1 {
    pattern '[a-zA-Z0-9-]+'; // Yang Parser accepted
}
type string2 {
    pattern '[a-zA-Z0-9-\_]+' // Yang Parser report as error;
}
The only difference between the two patterns is one '\_'.
So here I would like to figure out whether it is the last '-' or the last '\_', which trigger the validation error.
Because according to my understanding of your words, the two patterns should be wrong both.

Do I understand correctly?

**Comment by JanKoehnlein** [comment]
OK my bad. 

I tested with (this online regexp tester)[https://regex101.com/] and it seems to be valid. The minus after a character range seems to be valid even without quoting.
Regexp implementations vary a lot, and it seems that the regexp validator from EMF which we use does not support this. I am switching to Java's built-in `Pattern.compile` for validation.

https://github.com/theia-ide/yang-lsp/pull/93

**Comment by JanKoehnlein** [comment]
Re-reading the spes, YANG uses the XML schema regexp which states that `-` has to be quoted
https://www.w3.org/TR/2004/REC-xmlschema-2-20041028/#nt-charClassEsc

So pyang is wrong here. Closing.

**Comment by huyuwen** [comment]
Alright, I get your point. For the second pattern, I think you are right.
But regarding to the first pattern, the last '\-' should also be reported as an error, right?
type string1 {
pattern '[a-zA-Z0-9\-]+'; // Yang Parser accepted
}
type string2 {
pattern '[a-zA-Z0-9\-\_]+' // Yang Parser report as error;
}
Actually, my doubt is the two patterns are almost the same (both have incorrect '\-' without backslash).
Why one is valid and another is invalid?

**Comment by JanKoehnlein** [comment]
It's a bug in the EMF regexp validator we use. It is based on a stale version of Apache Xerces. Switching to a newer version of Xerces https://github.com/theia-ide/yang-lsp/pull/98

**Comment by JanKoehnlein** [comment]
Merged PR
